name: HPAdmin

on:
  push:
    branches: [master]
    paths: ['HPAdmin/**']
  pull_request:
    branches: [master]
    paths: ['HPAdmin/**']
    
defaults:
  run:
    working-directory: HPAdmin
    
jobs:

  build:
  
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x, 15.x]
        
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: npm ci
    - run: npm run build --if-present
          echo test, and deploy your project.
