name: HPCore

on:
  push:
    branches: [master]
    paths: ['HPCore/**']
  pull_request:
    branches: [master]
    paths: ['HPCore/**']

defaults:
  run:
    working-directory: HPCore

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: chmod +x ./gradlew
      - run: ./gradlew build
